import { callLLM } from "./llmClient.js";
import { CODEGEN_SYSTEM_PROMPT } from "./prompts/codegenSystemPrompt.js";
import { CodeFileMapSchema, type Brief, type AssetRef, type CodeFileMap } from "./schemas.js";
import * as ts from "typescript";

const MAX_CODEGEN_RETRIES = 3;

export function ensureRootFile(files: CodeFileMap, brief: Brief): CodeFileMap {
  if (files["Root.tsx"]) {
    return {
      ...files,
      "Root.tsx": enforceMainCompositionId(files["Root.tsx"]),
    };
  }

  console.log("[Codegen Middleware] Root.tsx was not generated by LLM. Generating fallback Root.tsx...");

  // Parse files for exported components
  const imports: string[] = [];
  const sequences: string[] = [];
  let currentFrame = 0;
  const fps = 30;

  // Track if we have an ambient background component
  let backgroundComponent: string | null = null;

  for (const [filename, content] of Object.entries(files) as Array<[string, string]>) {
    if (!filename.endsWith(".tsx")) continue;
    const moduleName = filename.replace(/\.tsx$/, "");

    // Regex to find named exports: export const MyComponent = ... or export function MyComponent() ...
    const exportRegex = /export\s+(?:const|function)\s+([A-Z]\w*)/g;
    let match: RegExpExecArray | null;
    const exportsInFile: string[] = [];

    while ((match = exportRegex.exec(content)) !== null) {
      exportsInFile.push(match[1]);
    }

    if (exportsInFile.length > 0) {
      const primaryComponent = exportsInFile[0];
      imports.push(`import { ${primaryComponent} } from "./${moduleName}";`);

      // Detect background files
      if (primaryComponent.toLowerCase().includes("background") || primaryComponent.toLowerCase().includes("ambient")) {
        backgroundComponent = primaryComponent;
      } else {
        // Assume default scene duration of 90 frames (3 seconds) if not mapped to a brief scene
        const durationInFrames = 90;
        sequences.push(`      <Sequence from={${currentFrame}} durationInFrames={${durationInFrames}}>
        <${primaryComponent} font="Inter" startFrame={0} />
      </Sequence>`);
        currentFrame += durationInFrames;
      }
    }
  }

  // Calculate total duration
  const totalDurationFrames = Math.max(90, currentFrame);

  const rootContent = `import React from "react";
import { Composition, AbsoluteFill, Sequence } from "remotion";
${imports.join("\n")}

const MainSequence: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#000000" }}>
      {/* Background layer */}
      ${backgroundComponent ? `<${backgroundComponent} />` : "<!-- No ambient background detected -->"}
      
      {/* Sequential scenes */}
${sequences.join("\n")}
    </AbsoluteFill>
  );
};

export const Root: React.FC = () => {
  return (
    <Composition
      id="Main"
      component={MainSequence}
      durationInFrames={${totalDurationFrames}}
      fps={${fps}}
      width={1920}
      height={1080}
    />
  );
};
`;

  return {
    ...files,
    "Root.tsx": rootContent,
  };
}

function enforceMainCompositionId(rootContent: string): string {
  return rootContent.replace(/id\s*=\s*"([^"]+)"/, 'id="Main"');
}

/**
 * AST-based Composition removal.
 * Removes all Composition imports and JSX elements from the given TypeScript source.
 * More reliable than regex since it respects TypeScript syntax.
 */
function stripComposition(content: string): string {
  const sourceFile = ts.createSourceFile(
    "temp.tsx",
    content,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX
  );

  const transformer: ts.TransformerFactory<ts.SourceFile> = (context) => {
    return (rootNode) => {
      function visit(node: ts.Node): ts.Node | undefined {
        // Remove Composition from import declarations
        if (ts.isImportDeclaration(node)) {
          const importClause = node.importClause;
          if (importClause?.namedBindings && ts.isNamedImports(importClause.namedBindings)) {
            const elements = importClause.namedBindings.elements.filter(
              (element) => element.name.text !== "Composition"
            );

            // If no imports remain, remove the entire import statement
            if (elements.length === 0) {
              return undefined;
            }

            // If some imports remain, update the import declaration
            if (elements.length !== importClause.namedBindings.elements.length) {
              return ts.factory.updateImportDeclaration(
                node,
                node.modifiers,
                ts.factory.updateImportClause(
                  importClause,
                  importClause.isTypeOnly,
                  importClause.name,
                  ts.factory.updateNamedImports(importClause.namedBindings, elements)
                ),
                node.moduleSpecifier,
                node.assertClause
              );
            }
          }
        }

        // Replace <Composition> JSX elements with null
        if (ts.isJsxElement(node) || ts.isJsxSelfClosingElement(node)) {
          const tagName = ts.isJsxElement(node)
            ? node.openingElement.tagName
            : node.tagName;

          if (ts.isIdentifier(tagName) && tagName.text === "Composition") {
            return ts.factory.createNull();
          }
        }

        return ts.visitEachChild(node, visit, context);
      }

      return ts.visitNode(rootNode, visit) as ts.SourceFile;
    };
  };

  const result = ts.transform(sourceFile, [transformer]);
  const transformedSourceFile = result.transformed[0];

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  let output = printer.printFile(transformedSourceFile);

  result.dispose();

  // Post-process: fix any broken syntax patterns that might remain
  output = output.replace(/\(\)\s*=>\s*;/g, "() => null;");
  output = output.replace(/\(\s*\)\s*=>\s*\)/g, "() => null)");
  output = output.replace(/return\s*;/g, "return null;");

  return output;
}

function sanitizeAllFiles(files: CodeFileMap): CodeFileMap {
  const result: CodeFileMap = {};
  for (const [filename, content] of Object.entries(files)) {
    result[filename] = stripComposition(content);
  }
  return result;
}

function extractCompAttrs(content: string): {
  componentName: string;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
} {
  const defs = { componentName: "Main", durationInFrames: 90, fps: 30, width: 1920, height: 1080 };

  const compName = content.match(/component\s*=\s*\{(\w+)\}/);
  if (compName) defs.componentName = compName[1];

  const dur = content.match(/durationInFrames\s*=\s*\{(\d+)\}/);
  if (dur) defs.durationInFrames = Number(dur[1]);

  const f = content.match(/fps\s*=\s*\{(\d+)\}/);
  if (f) defs.fps = Number(f[1]);

  const w = content.match(/width\s*=\s*\{(\d+)\}/);
  if (w) defs.width = Number(w[1]);

  const h = content.match(/height\s*=\s*\{(\d+)\}/);
  if (h) defs.height = Number(h[1]);

  return defs;
}

function injectRootComposition(
  files: CodeFileMap,
  componentName: string,
  durationInFrames: number,
  fps: number,
  width: number,
  height: number,
): CodeFileMap {
  const rootContent = files["Root.tsx"];
  if (!rootContent) return files;

  // Ensure Composition is imported (stripComposition may have removed it)
  const hasCompImport = /import\s*\{[^}]*\bComposition\b[^}]*\}\s*from\s*["']remotion["']/.test(rootContent);
  let withImport = rootContent;
  if (!hasCompImport) {
    const hasAnyRemotionImport = /import\s*\{[^}]*\}\s*from\s*["']remotion["']/.test(rootContent);
    if (hasAnyRemotionImport) {
      withImport = rootContent.replace(
        /(import\s*\{)([^}]*)(\}\s*from\s*["']remotion["'])/,
        "$1Composition, $2$3",
      );
    } else {
      withImport = `import { Composition } from "remotion";\n${rootContent}`;
    }
  }

  // Build a minimal Root export with exactly one Composition
  const newRoot = `\n\nexport const Root: React.FC = () => {
  return (
    <Composition
      id="Main"
      component={${componentName}}
      durationInFrames={${durationInFrames}}
      fps={${fps}}
      width={${width}}
      height={${height}}
    />
  );
};`;

  // Remove any existing Root export (exact name, not prefix like RootFallback)
  const cleaned = withImport.replace(
    /export\s+(?:const|function|default)\s+Root\b[\s\S]*?(?=(?:\nexport|\n\/\/|\n\/\*|\n$|$))/g,
    "",
  ).trimEnd();

  return {
    ...files,
    "Root.tsx": cleaned + newRoot,
  };
}

// Find the best inner component name from all source files.
// Returns the component used in Root.tsx's <Composition component={X}>,
// or falls back to the first non-background export from any file.
function resolveInnerComponent(originalFiles: CodeFileMap, sanitizedFiles: CodeFileMap): string {
  // 1. Try original Root.tsx for component={X} (pre-sanitized)
  const origRoot = originalFiles["Root.tsx"];
  if (origRoot) {
    const m = origRoot.match(/component\s*=\s*\{(\w+)\}/);
    if (m) return m[1];
  }

  // 2. Try sanitized Root.tsx (in case injectRootComposition already set it)
  const sanRoot = sanitizedFiles["Root.tsx"];
  if (sanRoot) {
    const m = sanRoot.match(/component\s*=\s*\{(\w+)\}/);
    if (m) return m[1];
  }

  // 3. Find the first component declaration (exported or not) from any file
  for (const [filename, content] of Object.entries(sanitizedFiles)) {
    if (!filename.endsWith(".tsx") || filename === "Root.tsx") continue;
    const allCompRegex = /(?:export\s+)?(?:const|function|default)\s+([A-Z]\w*)/g;
    let match: RegExpExecArray | null;
    while ((match = allCompRegex.exec(content)) !== null) {
      const name = match[1];
      if (!name.toLowerCase().includes("background") && !name.toLowerCase().includes("ambient")) {
        return name;
      }
    }
  }

  return "Main";
}

function findExistingComponent(
  files: CodeFileMap,
  componentName: string,
): { file: string; exportName: string } | null {
  for (const [filename, content] of Object.entries(files)) {
    if (!filename.endsWith(".tsx")) continue;
    // Check both exported and non-exported declarations
    const allCompRegex = /(?:export\s+)?(?:const|function|default)\s+([A-Z]\w*)/g;
    let match: RegExpExecArray | null;
    while ((match = allCompRegex.exec(content)) !== null) {
      if (match[1] === componentName) {
        return { file: filename, exportName: componentName };
      }
    }
  }
  return null;
}

export async function generateCode(
  brief: Brief,
  assets: AssetRef[] = [],
  modelName?: string,
  pdfContent?: string,
  width: number = 1920,
  height: number = 1080,
): Promise<CodeFileMap> {
  let userContent = JSON.stringify({ brief, assets }, null, 2);
  if (pdfContent) {
    const truncated = pdfContent.length > 4000 ? pdfContent.slice(0, 4000) + "\n[...truncated...]" : pdfContent;
    userContent += `\n\n--- EXTRACTED PDF CONTENT ---\n${truncated}\n--- END PDF CONTENT ---\nUse this PDF content as the primary source for scene data, statistics, and narrative.`;
  }

  const systemPrompt = CODEGEN_SYSTEM_PROMPT
    .replace(/\{WIDTH\}/g, String(width))
    .replace(/\{HEIGHT\}/g, String(height))
    .replace(/\{SAFE_WIDTH\}/g, String(width - 160))
    .replace(/\{SAFE_HEIGHT\}/g, String(height - 160));

  for (let attempt = 0; attempt <= MAX_CODEGEN_RETRIES; attempt++) {
    const messages = [
      { role: "system" as const, content: systemPrompt },
      { role: "user" as const, content: `Generate Remotion React code for this Creative Brief:\n${userContent}` },
    ];

    const responseText = await callLLM(messages, true, modelName);
    let json: any;

    try {
      json = JSON.parse(responseText);
    } catch {
      if (attempt < MAX_CODEGEN_RETRIES) {
        console.warn(`[Codegen] JSON parse failed on attempt ${attempt + 1}, retrying...`);
        continue;
      }
      throw new Error(`Failed to parse LLM response as JSON after ${MAX_CODEGEN_RETRIES + 1} attempts.`);
    }

    try {
      const files = CodeFileMapSchema.parse(json);

      const cleanedFiles: CodeFileMap = {};
      for (const [key, val] of Object.entries(files)) {
        const cleanKey = key.replace(/^src\//, "");
        cleanedFiles[cleanKey] = val;
      }

      // Extract Composition attrs from ORIGINAL Root.tsx (pre-sanitization).
      // This preserves the inner component name that sanitization would strip.
      const origRoot = cleanedFiles["Root.tsx"];
      const origAttrs = origRoot ? extractCompAttrs(origRoot) : null;

      const sanitized = sanitizeAllFiles(cleanedFiles);
      const withRoot = ensureRootFile(sanitized, brief);

      // Resolve the best component name — prefer the one from original Root.tsx
      const innerCompName = resolveInnerComponent(cleanedFiles, withRoot);

      // Verify the resolved component actually exists in the file map
      const componentExists = findExistingComponent(withRoot, innerCompName);
      const finalCompName = componentExists ? innerCompName : resolveInnerComponent(withRoot, withRoot);

      const dur = origAttrs?.durationInFrames ?? 90;
      const f = origAttrs?.fps ?? 30;
      const w = origAttrs?.width ?? 1920;
      const h = origAttrs?.height ?? 1080;

      return injectRootComposition(withRoot, finalCompName, dur, f, w, h);
    } catch (parseErr: any) {
      if (attempt < MAX_CODEGEN_RETRIES) {
        console.warn(`[Codegen] Schema validation failed on attempt ${attempt + 1}: ${parseErr.message}`);
        continue;
      }
      throw new Error(`Generated code failed validation after ${MAX_CODEGEN_RETRIES + 1} attempts: ${parseErr.message}`);
    }
  }

  throw new Error("Codegen failed unexpectedly.");
}
